src/Entity/Formation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;


/**
 * @ORM\Entity(repositoryClass="App\Repository\FormationRepository")
 */
class Formation
{
    //constantes car on sait que ces valeurs ne seront jamais changées
    const LANGUE = [
        ''=>'Choisir une Langue',
        'Anglais' => 'Anglais',
        'Français'=> 'Français'
    ];

    const LEVEL = [
        ''=>'Choisir un niveau',
        'Beginner Level'=> 'Débutant',
        'Intermediate Level'=> 'Intermediaire',
        'Expert Level'=>'Avancé',

    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $note;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $aviable;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at= new \DateTime();
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $langue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $level;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="formations")
     */
    private $categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug()
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAviable(): ?bool
    {
        return $this->aviable;
    }

    public function setAviable(bool $aviable): self
    {
        $this->aviable = $aviable;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLangue(): ?string
    {
        return $this->langue;
    }

    public function getLangueType()
    {
        return self::LANGUE[$this->langue];
    }
    public function setLangue(string $langue): self
    {
        $this->langue = $langue;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function getLevelType():string
    {
        return self::LEVEL[$this->level];
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }



}

templates/pages/formation.html.twig
{% block title 'Les formations' %}
{% extends 'base.html.twig' %}

{% block body %}

    <!--Cette page affiche les formations -->
    {{ include('pages/CommonTemplates/_filtreTemplate.html.twig') }}
    <div class="container">
        <div class="sous-titre" style="width: 60%;margin-bottom: 30px">
            <h2 style="font-size: 50px">Toutes les formations </h2>
        </div>
        <div class="row" style="background-color: #f7f7f7;">
            {% for formation in formations %}
                <div class="col-sm-4 col-md-3">
                    {{ include ('pages/CommonTemplates/_afficheFormations.html.twig') }}
                </div>
            {% endfor %}
        </div>
        <div class="pagination container">
            {{ knp_pagination_render(formations) }}
        </div>
    </div>


{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}

   <section id="section-1">
       {{ include('pages/CommonTemplates/_filtreTemplate.html.twig') }}
   </section>
   <!--Ce bout de code affiche dans la page d'accueil les catégories tendances et les formations les mieux notées dans un carrousel -->
   <section id=section-2 class="container">
      <div class="sous-titre">
         <h2>Les catégories tendances</h2>
      </div>
      {{ include ('pages/CommonTemplates/_carousel.html.twig') }}
   </section>


   <section id=section-3 class="container">
      <a class="btn btn-primary" href="{{ path('categorie.route') }}">Voir toutes les catégories</a>
   </section>


   <section id=section-4 class="container">
      <div class="sous-titre">
         <h2>Les formations les mieux notées</h2>
      </div>
      {{ include ('pages/CommonTemplates/_carousel.html.twig',{nomCarousel :'Carousel2',nomVar:formationsMieuxNotees}) }}
   </section>
{% endblock %}

templates/pages/informations.html.twig
{% extends 'base.html.twig' %}

{% block body %}   
    <div class="container" style="margin-top: 150px">
        <div class="description px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Qui sommes-nous?</h1>
            <p class="lead">Jidu est une start-up spécialisée dans le Machine learning et l’intelligence artificielle pour l’éducation, l’apprentissage et la formation, et souhaite accompagner l’apprenant dans une montée en compétences continue, personnalisée et qui prend en compte l’évolution de ses usages.</p>
        </div>

        <hr class="clearfix w-100 d-md-none pb-3">
        <div class="container text-center">
            <div class="row d-flex justify-content-center">
                <div class="col-md-4 color-class">
                    <div class="card" style="width:400px">
                        <img class="img-information" src="{{ asset('images/travailleur.png') }}" alt="Card image">
                        <div class="card-body">
                            <h4 class="card-title">Marouene Chaibi</h4>
                            <p class="card-text">Directeur général</br>&</br>Cofondateur de la start-up</p>
                            <a href="#" class="btn btn-primary">Détails</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 color-class">
                    <div class="card" style="width:400px">
                        <img class="img-information" src="{{ asset('images/travailleur.png') }}" alt="Card image">
                        <div class="card-body">
                            <h4 class="card-title">Fabien Mallet</h4>
                            <p class="card-text">Directeur marketing</br>&</br>Cofondateur de la start-up</p>
                            <a href="#" class="btn btn-primary">Détails</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 color-class">
                    <div class="card" style="width:400px">
                        <img class="img-information" src="{{ asset('images/travailleur.png') }}" alt="Card image">
                        <div class="card-body">
                            <h4 class="card-title">Mthandazo Ndhlovu</h4>
                            <p class="card-text">Directeur de la technologie</br>&</br>Cofondateur de la start-up</p>
                            <a href="#" class="btn btn-primary">Détails</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

        <hr class="clearfix w-100 d-md-none pb-3">

        <div class="contact px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h4 class="display-5>Pour nous contacter</h4>
            <p class="lead">Vous pouvez nous contacter par téléphone au 01 23 45 67 89 ou bien par mail à l'adresse suivante techOver@techover.com</p>
        </div>
    </div>  
{% endblock %}

templates/pages/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}

{#        <div class="container" style="margin-top: 120px">#}
{#            <div class="sous-titre" style="width: 60%;margin-bottom: 30px">#}
{#                <h1 style="text-align: center;font-size: 50px;">{{ formation.title }}</h1>#}
{#            </div>#}
{#            <img src="{{ asset(''~formation.image~'') }}" class ="center" alt="image" style="margin-top:50px;width:40%;text-align: center">#}
{#            <div class="text-primary" style="font-size:2rem"> Langue :{{ formation.langue }}</div>#}
{#            <h3>{{ formation.note }} étoiles</h3>#}
{#            <h4>Niveau : {{ formation.level}}</h4>#}
{#            <a href="{{ path( 'categorie.show',{id : formation.categorie.id ,slug : formation.categorie.slug}) }}">{{formation.categorie}}</a>#}
{#            <h2 style="text-align: left">Description</h2>#}
{#            <p style="text-align: justify">{{ formation.description }}</p>#}
{#            <a href="{{ formation.url }}" style="margin-top: 50px ;width:50%" target="_blank" class="btn btn-primary">Accéder à cette formation</a>#}
{#        </div>#}

    


    <div class="jumbotron" style="margin-top: 90px">

        <div class="container">

            <div class="row">
                <div class="col-md-8">
                    <img src="{{ asset(''~formation.image~'') }}" class ="center img-thumbnail" alt="image" style="width:80%;text-align: center">
                </div>
                <div class="col-md-4" style="margin-top: 40px">
                    <div class="sous-titre" style="width: 90%;margin-bottom: 30px">
                        <h1 style="text-align: center;font-size: 25px;">{{ formation.title }}</h1>
                    </div>
                    <h2 style="text-align: center;font-size: 25px;">{{  formation.note|rating(5, "fa-3x")  }}</h2>
                    <div class="text-primary" style="font-size: 4rem;font-weight: bold"></div>
                    <a href="{{ formation.url }}" style="margin-top: 50px ;width:65%" target="_blank" class="btn btn-primary">Accéder à cette formation</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">

        <h2 style="text-align: left">Description</h2>

        <p>
            {{ formation.description | nl2br }}
        </p>
        <hr class="my-4" style="border-top-color: #999999" >
        <div class="row " style="background-color: #ECECEC">
            <div class="col-md-12">
                <h2>Spécificités</h2>

                <table class="table table-striped">
                    <tr>
                        <td>Catégorie</td>
                        <td>  <a href="{{ path( 'categorie.show',{id : formation.categorie.id ,slug : formation.categorie.slug}) }}">{{formation.categorie}}</a>
                        </td>
                    </tr>
                    <tr>
                        <td>Langue</td>
                        <td>{{ formation.langue }}</td>
                    </tr>

                    <tr>
                        <td>Niveau</td>
                        <td>{{ formation.levelType }}</td>
                    </tr>



                </table>






            </div>



        </div>


    </div>

{% endblock %}